server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
---
# eureka configuration -> from config server
---
# config server configuration
spring:
  config:
    import: configserver:http://localhost:9296
---
# api gateway configuration
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: ORDER-SERVICE
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/order/**

          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payment/**

          - id: PRODUCT-SERVICE
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/product/**
