version: "3"
services:

  mongodb:
    image: mongo:7.0
    container_name: "mongodb"
    ports:
      - "27017:27017"

  springboot-mongodb-app:
    image: springboot-mongodb:1.0
    container_name: "springboot-mongodb-app"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb