server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost:3306}/demo_for_all
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

---
# eureka configuration -> from config server

---
# config server configuration
spring:
  config:
    import: configserver:http://localhost:9296

---
#resilience4j configuration
resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50 #50%
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
