spring:
  application:
    name: Task2-SecurityAuditing
---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
#    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

api:
  endpoint:
    base-url: /api/v1
---
management:
  endpoint:
    web:
      exposure: includeloggers
    loggers:
      enabled: true
---
