spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_for_all
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html

filter:
  token:
    prefix: "Bearer "
  paths:
    exclude:
      url: http://localhost:8080/swagger-ui.html, http://localhost:8080/swagger-ui/index.html, http://localhost:8080/api/v1/auth, http://localhost:8080/swagger-ui/swagger-initializer.js, http://localhost:8080/v3/api-docs/swagger-config, http://localhost:8080/v3/api-docs